name: Bug report
description: "Report a bug with Minimal"
labels: ["bug"]
assignees:
  - kepano
body:
  - type: markdown
    attributes:
      value: |
        Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian
  - type: dropdown
    id: default-present
    attributes:
      label: Is the bug present when using the default theme?
      options:
         - Yes
         - No
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a description of the bug and steps to reproduce
      placeholder: 
    validations:
      required: true
  - type: input 
    id: version
    attributes:
      label: Minimal version
      description: What version of Minimal are you using? Can be found by going to Appearance > Manage
      placeholder: 5.2.10
    validations:
      required: true
  - type: input 
    id: obsidian-version 
    attributes:
      label: Obsidian Version
      placeholder: 0.15.2
    validations:
      required: true
