name: Bug report
description: "Report a bug with Minimal"
labels: ["bug"]
assignees:
  - kepano
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: default-present
    attributes:
      label: Is the bug present when using the default Obsidian theme?
      description: Disable plugins and snippets that could be causing a conflict, and test using the default theme
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input 
    id: version
    attributes:
      label: Minimal theme version
      description: What version of Minimal theme are you using? Can be found by going to `Appearance > Manage`. Make sure you have updated to the latest version of the theme.
      placeholder: 5.2.10
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a description of the bug and steps to reproduce. If applicable, add screenshots to help explain your problem.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: debug-info
    attributes:
      label: Debug info
      description: Paste your debug info below, which can be accessed in Obsidian with Ctrl/Cmd-P, enter `Show debug info`, and select `Copy to clipboard`
      placeholder: 
    validations:
      required: true
