blank_issues_enabled: false
contact_links:
  - name: Obsidian Discord
    url: https://discord.com/channels/686053708261228577/931008597557649410
    about: Please ask and answer questions here
  - name: Minimal Documentation
    url: https://minimal.guide/Help
    about: More details about getting help with Minimal